CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(50),
  lastname VARCHAR(50),
  email VARCHAR(100) UNIQUE,
  password VARCHAR(255),
  role VARCHAR(20),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(10),
  firstname VARCHAR(50),
  lastname VARCHAR(50),
  email VARCHAR(100),
  telephone VARCHAR(20),
  company VARCHAR(100),
  type VARCHAR(20),
  assigned_to INT,
  created_by INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  contact_id INT,
  comment TEXT,
  created_by INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
